### ISSUE TITLE
Bug: Unable to create new card from a template

### ISSUE THREAD

**Issue by nishantwrp** [mattermost/focalboard#1888]
## Steps to reproduce the behavior

1. Try to create a new card from a template
2. See error

## Screenshots

I get this card when I try to create a new card from a pre-existing template.

<img width="998" alt="Screenshot 2021-11-29 at 11 34 47 PM" src="https://user-images.githubusercontent.com/36989112/143920159-d921892d-5863-426b-bcbc-109dd018832a.png">

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.11.0
 - Browser and OS: Safari & MacOS

**Comment by jespino** [comment]
I can't not reproduce this locally in the main branch or in the release-0.11 branch :(

**Comment by nishantwrp** [comment]
I can still reproduce this on my hosted instance. Both the templates that existed before upgrading and the ones created after upgrading show the same error on creating a card with them.

**Comment by jespino** [comment]
Thanks @nishantwrp, I going to try to check that in Safari. Thanks for the heads up. Are you using the 0.11rc1? or an specific commit?

**Comment by nishantwrp** [comment]
0.11rc1

**Comment by sbishel** [comment]
I don't think its exactly the same, but related to https://github.com/mattermost/focalboard/issues/1922

Duplicating card from another card or template.

**Comment by sbishel** [comment]
This appears to have been fixed by this PR - https://github.com/mattermost/focalboard/pull/1937 
0.11.0-rc2 should have the fix.

**Comment by ogi-m** [comment]
@sbishel I can still reproduce this with RC2

**Comment by sbishel** [comment]
Thanks @ogi-m. We'll keep it open.

**Comment by ogi-m** [comment]
Steps to repro (applies to plugin also):

1. Create a board from a template
2. Open one the pre-made cards
3. Click on `...` in the top right > New template from card
4. Observe the error
5. Close the card dialog and click on the downward arrow next to "New" button on the board
6. Select the card template created from the card in step 3
7. Observe the error

**Comment by wuwinson** [comment]
Repro'ed on v0.11 RC2 plugin following @ogi-m's steps above. Template still gets created in step 3, and card still gets created in step 6. See video for more details.

When creating a card from an existing template from the blue drop-down on the board, error still appears for a split second, but is replaced by the card template (see the 27 sec mark).

https://user-images.githubusercontent.com/93531870/145282086-67ce330b-b9e1-4e8e-bf0f-302b253f299c.mov

**Comment by harshilsharma63** [comment]
> Steps to repro (applies to plugin also):
> 
>     1. Create a board from a template
> 
>     2. Open one the pre-made cards
> 
>     3. Click on `...` in the top right > New template from card
> 
>     4. Observe the error
> 
>     5. Close the card dialog and click on the downward arrow next to "New" button on the board
> 
>     6. Select the card template created from the card in step 3
> 
>     7. Observe the error

Thanks @ogi-m for the steps! This was very helpful.

**Comment by harshilsharma63** [comment]
Fixed and merged in main and cherrypicked in `release-0.11`.

**Comment by nishantwrp** [comment]
Just updated my server to the latest release. Now, the error just appears briefly and then I can edit the card. Still, the content of the new card is empty. The template content doesn't get filled in the new card.  /cc @harshilsharma63 @ogi-m

**Comment by harshilsharma63** [comment]
@nishantwrp thanks for reporting. I'll check that.

**Comment by nishantwrp** [comment]
Hi @harshilsharma63, did you get a chance to look at this? This issue is still not fixed for me in the latest `0.11` release.
