### ISSUE TITLE
Bug: After removed from board, you should land to first board/view in your list

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2962]
## Steps to reproduce the behavior

1. User A adds User B to board
2. User B goes to the board
3. User A removes User B from the board
4. User B lands on template picker

## Expected behavior
User B should land on the first board/view in his list. If he has no boards, then he can land to the template picker.

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac
 
## Additional context (optional)
SEV3

**Comment by Pinjasaur** [comment]
paired on this with @mgdelacroix today and while testing/repro-ing we uncovered a separate bug related to websockets & memberships: #3477

based on progress so far, it appears that `getCurrentBoard` https://github.com/mattermost/focalboard/blob/4b5152940db748bd1b29b8f5515cf5c2473fc31c/webapp/src/components/workspace.tsx#L37 is returning falsy so the component is defaulting to rendering the template selector: https://github.com/mattermost/focalboard/blob/4b5152940db748bd1b29b8f5515cf5c2473fc31c/webapp/src/components/workspace.tsx#L111 but the URL _isn't_ updating so upon refreshing the page it tries to route to a now-invalid board ID and renders the error page

I pushed the wip commit progress to https://github.com/mattermost/focalboard/tree/gh-2962-removed-from-board

**Comment by sbishel** [comment]
Retested on latest https://boards-bugbash73.test.mattermost.cloud/
- this is still an issue.
